routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
Route::resource('books', BookController::class);
use App\Http\Controllers\CreaterBookController;
Route::resource('creater_books', CreaterBookController::class);
use App\Http\Controllers\UserController;
Route::resource('users', UserController::class);
Route::post('/', '\App\Http\Controllers\UserController@login');
Route::get('/', '\App\Http\Controllers\UserController@login');
Route::get('/logout', ['as'=>'logout','uses' => '\App\Http\Controllers\BookController@logout']);
Route::post('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/hello', '\App\Http\Controllers\UserController@login');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
		'role_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	 
    public function index()
    {
		
    }

    public function login(Request $request)
    {
		if ($request->isMethod('post')) {
			$user = User::where('email', $request->username)
					  ->where('password',md5($request->password))
					  ->first();
			if(!empty($user)){
				Auth::login($user);			
				return redirect('/books');		 				
			}else{
				return view('login.index',array("message"=>"Invalid Email Or Password"));						
			}		  
		}
		return view('login.index',array("message"=>""));		
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request){
		//echo Auth::user()->role_id;
		if (Auth::user()->role_id == 1){
			
		}else{
			return redirect('/');			
		}
			
		$users = User::all();
        return view('users.create',compact('users'));		
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		if (Auth::user()->role_id == 1){
			
		}else{
			return redirect('/');			
		}	
        $request->validate([
            'create_name' => 'required',
            'email' => 'required',
            'password' => 'required'					
        ]);		
		$users = $request->all();
		$users['password'] = md5($users['password']);
			$check_email=DB::table('users')
				->where('email', $request->email)
				->first();
			if(!empty($check_email)){
				return redirect()->route('users.create')
                        ->with('success','Email is already exists in the data.');					
			}else{
				User::create($users);				
			}		
        return redirect()->route('users.create')
                        ->with('success','Users created successfully.');		
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy(User $User)
    {
        $User->delete();
        return redirect()->route('users.create')
                        ->with('success','Users deleted successfully');
    }	
	
	public function reset_password(Request $request){
		if ($request->isMethod('post')) {
			$check_email=DB::table('users')
				->where('email', $request->email)
				->first();
			if(!empty($check_email)){
			DB::table('users')
				->where('email', $request->email)
				->update(['password' => md5($request->password)]);									
				return view('users.reset_password',["message"=>"Reset Password Telah Berhasil"]);					
			}else{
				return view('users.reset_password',["message"=>"Email tidak ditemukan"]);									
			}
		}
        return view('users.reset_password');				
	}
	
}

resources/views/users/create.blade.php
@extends('template')
 
@section('content')
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create User</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('books.index') }}">Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{route('users.store')}}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama User:</strong>
                <input type="text" name="name" class="form-control" placeholder="Nama User">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Role Id:</strong>
				<select name="role_id" class="form-control">
					<option value="1">Admin</option>
					<option value="2">User</option>
				</select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Password:</strong>
                <input type="text" name="password" class="form-control" placeholder="Password">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th>User Name</th>
            <th>Role Id</th>
            <th>Action</th>
        </tr>
		@php($count=0)
        @foreach ($users as $user)
		@php($count++)
        <tr>
            <td class="text-center">{{$count}}</td>
            <td>{{ $user->name }}</td>
            <td>
			@if($user->role_id == 1)
				Admin 
			@else
				User
			@endif	
			</td>
            <td class="text-center">
                <form action="{{ route('users.destroy',$user->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>
            </td>			
        </tr>
        @endforeach
    </table>
@endsection

resources/views/users/reset_password.blade.php
@extends('template')
 
@section('content')
@if(empty($message))

@else
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif
<form action="" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email</strong>
                <input type="text" name="email" class="form-control" placeholder="Email">
            </div>
            <div class="form-group">
                <strong>New Password</strong>
                <input type="text" name="new_password" class="form-control" placeholder="New Password">
            </div>
        </div>
    </div>
	<input type="submit" name="submit" value="Reset Password" class="form-control"/>
</form>
@endsection