routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
Route::resource('books', BookController::class);
use App\Http\Controllers\CreaterBookController;
Route::resource('creater_books', CreaterBookController::class);
use App\Http\Controllers\UserController;
Route::resource('users', UserController::class);
Route::post('/', '\App\Http\Controllers\UserController@login');
Route::get('/', '\App\Http\Controllers\UserController@login');
Route::get('/logout', ['as'=>'logout','uses' => '\App\Http\Controllers\BookController@logout']);
Route::post('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/hello', '\App\Http\Controllers\UserController@login');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
	
    protected $fillable = [
		'id_create_book',
        'book_name',
		'book_information'
    ];	
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\CreaterBook;
use Illuminate\Support\Facades\Auth;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	public function __construct(){
		if (!!Auth::user()){
			return redirect('/');			
		}		
	}	 
	 
    public function index()
    {
       $books = Book::join('creater_books', 'books.id_create_book', '=', 'creater_books.id')
                ->get(['books.*', 'creater_books.create_name']);
        return view('books.index',compact('books'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
 
    public function create(){
        $createrbook = CreaterBook::all();		
        return view('books.create',compact('createrbook'));
    }
	 
    public function store(Request $request)
    {
        $request->validate([
            'book_name' => 'required'					
        ]);	
        Book::create($request->all());
        return redirect()->route('books.index')
                        ->with('success','Book created successfully.');
    }
 
    public function show(Book $book)
    {
        return view('books.show',compact('book'));
    }
 
    public function edit(Book $book)
    {
        $createrbook = CreaterBook::all();				
        return view('books.edit',compact('book','createrbook'));
    }
 
    public function update(Request $request, Book $Book)
    {
        $request->validate([
            'book_name' => 'required'
        ]);
 
        $Book->update($request->all());
 
        return redirect()->route('books.index')
                        ->with('success','Book updated successfully');
    }
 
    public function destroy(Book $Book)
    {
        $Book->delete();
        return redirect()->route('books.index')
                        ->with('success','Book deleted successfully');
    }
	
	public function logout(Request $request){
		Auth::logout();
	//	echo "hoho";
		return redirect('/');
	}
}

resources/views/books/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Book</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('books.index') }}">Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('books.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pengarang Buku:</strong>
				<select name="id_create_book" class="form-control">
					@foreach ($createrbook as $create)
						<option value="{{$create->id}}">{{$create->create_name}}</option>
					@endforeach					
				</select><br>
                <strong>Nama Buku:</strong>
                <input type="text" name="book_name" class="form-control" placeholder="Nama Buku">
                <strong>Informasi Buku:</strong>
                <input type="text" name="book_information" class="form-control" placeholder="Informasi Buku">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/books/edit.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Edit Book</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
 
    <form action="{{ route('books.update',$book->id) }}" method="post">
        @csrf
        @method('PUT')
 
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Pengarang Buku:</strong>
				<select name="id_create_book" class="form-control">
					@foreach ($createrbook as $create)
						@if ($create->id == $book->id_create_book)
							<option value="{{$create->id}}" selected>{{$create->create_name}}</option>
						@else
							<option value="{{$create->id}}">{{$create->create_name}}</option>	
						@endif							
					@endforeach					
				</select>
				<script>document.getElementById('id_create_book').value='{{ $book->id_create_book }}';</script>
				<br>				
                    <strong>Buku:</strong>
                    <input type="text" name="book_name" value="{{ $book->book_name }}" class="form-control" placeholder="Book Name">
				<br>				
                    <strong>Informasi Buku:</strong>
                    <input type="text" name="book_information" value="{{ $book->book_information }}" class="form-control" placeholder="Book Information">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
 
    </form>
@endsection

resources/views/books/index.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Perpustakaan Sekolah</h2>
            </div>
			@if (Auth::user()->role_id == 1)
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('users.create') }}">Create User</a>
            </div><br><br>				
			@endif	
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('books.create') }}">Create Buku</a>
            </div><br><br>
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('creater_books.create') }}">Create Pencipta Buku</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th>Nama Pencipta</th>
            <th>Nama Buku</th>
            <th>Informasi Buku</th>
            <th width="280px"class="text-center">Action</th>
        </tr>
        @foreach ($books as $book)
        <tr>
            <td class="text-center">{{ ++$i }}</td>
            <td>{{ $book->create_name }}</td>
            <td>{{ $book->book_name }}</td>
            <td>{{ $book->book_information }}</td>
            <td class="text-center">
                <form action="{{ route('books.destroy',$book->id) }}" method="POST">
                    <a class="btn btn-primary btn-sm" href="{{ route('books.edit',$book->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
	<a class="btn btn-success" href="logout">Logout</a>
@endsection

resources/views/books/show.blade.php
@extends('template')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Show Book</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>
 
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Book:</strong>
				{{ $book->book_name }}
            </div>
        </div>
    </div>
@endsection