routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
Route::resource('books', BookController::class);
use App\Http\Controllers\CreaterBookController;
Route::resource('creater_books', CreaterBookController::class);
use App\Http\Controllers\UserController;
Route::resource('users', UserController::class);
Route::post('/', '\App\Http\Controllers\UserController@login');
Route::get('/', '\App\Http\Controllers\UserController@login');
Route::get('/logout', ['as'=>'logout','uses' => '\App\Http\Controllers\BookController@logout']);
Route::post('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/reset_password', ['as'=>'logout','uses' => '\App\Http\Controllers\UserController@reset_password']);
Route::get('/hello', '\App\Http\Controllers\UserController@login');

app/Models/CreaterBook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CreaterBook extends Model
{
    use HasFactory;
	
    protected $fillable = [
        'create_name'
    ];		
}

app/Http/Controllers/CreaterBookController.php
<?php

namespace App\Http\Controllers;
use App\Models\CreaterBook;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CreaterBookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	public function __construct(){
		if (!!Auth::user()){
			return redirect('/');			
		}		
	}	 
	 	 
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { 
		$createrbooks=CreaterBook::all();
        return view('creater_books.create',compact('createrbooks'));		
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        CreaterBook::create($request->all());
        return redirect()->route('creater_books.create')
                        ->with('success','Penulis Buku created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	
    public function destroy(CreaterBook $CreaterBook)
    {
        $CreaterBook->delete();
        return redirect()->route('creater_books.create')
                        ->with('success','Creater Book deleted successfully');
    }	
}

resources/views/creater_books/create.blade.php
@extends('template')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create Pencipta Buku</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('books.index') }}">Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{route('creater_books.store')}}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Pencipta Buku:</strong>
                <input type="text" name="create_name" class="form-control" placeholder="Nama Pencipta Buku">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th>Nama Pencipta Buku</th>
            <th>Action</th>
        </tr>
		@php($count=0)
        @foreach ($createrbooks as $createrbook)
		@php($count++)
        <tr>
            <td class="text-center">{{$count}}</td>
            <td>{{ $createrbook->create_name }}</td>
            <td class="text-center">
                <form action="{{ route('creater_books.destroy',$createrbook->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                </form>
            </td>			
        </tr>
        @endforeach
    </table>
@endsection